services:
  sql-data-generator:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: sql-data-generator
    ports:
      - '32023:32023'
    environment:
      PORT: '32023'
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped
