import { DataTypeDefinition, SEMANTIC_DATA_TYPES } from './types';
import type { SemanticDataType } from './types';

export const SUPPORTED_SEMANTIC_TYPES = [...SEMANTIC_DATA_TYPES];

export const DATA_TYPE_DEFINITIONS: DataTypeDefinition[] = [
  {
    value: 'unknown',
    displayName: 'NULL',
    description: 'Always generates NULL.\nExample: NULL',
    groups: ['Basic'],
  },
  {
    value: 'guid',
    displayName: 'GUID',
    description: 'UUID-style identifier.\nExample: 550E8400-E29B-41D4-A716-446655440000',
    groups: ['Basic', 'IT'],
  },
  {
    value: 'digitSequence',
    displayName: 'Digit Sequence',
    description: 'Pattern string with references.\nExample: Ticket-391-ajQ',
    groups: ['Basic', 'IT'],
  },
  {
    value: 'formula',
    displayName: 'Formula',
    description: 'Calculated from columns.\nExample: quantity * unit_price',
    groups: ['Advanced'],
  },
  {
    value: 'sequence',
    displayName: 'Sequence',
    description: 'Incrementing number sequence.\nExample: 1, 2, 3, 4',
    groups: ['Basic'],
  },
  {
    value: 'dateTime',
    displayName: 'Date Time',
    description: 'Date or datetime value.\nExample: 2025-03-08',
    groups: ['Basic'],
  },
  {
    value: 'boolean',
    displayName: 'Boolean',
    description: 'True or false value.\nExample: true / false',
    groups: ['Basic', 'IT'],
  },
  {
    value: 'number',
    displayName: 'Number',
    description: 'Number with min/max.\nExample: 42, 99.5',
    groups: ['Basic', 'Commerce'],
  },
  {
    value: 'text',
    displayName: 'Text',
    description: 'Generic text value.\nExample: lorem ipsum',
    groups: ['Basic'],
  },
  {
    value: 'url',
    displayName: 'URL',
    description: 'Website URL.\nExample: https://example.com/product/1',
    groups: ['Basic', 'IT'],
  },
  {
    value: 'customList',
    displayName: 'Custom List',
    description: 'Values you enter manually.\nExample: admin,user,guest',
    groups: ['Basic'],
  },
  {
    value: 'fullName',
    displayName: 'Full Name',
    description: 'Person full name.\nExample: Nguyen Van A',
    groups: ['Personal'],
  },
  {
    value: 'firstName',
    displayName: 'First Name',
    description: 'Person first name.\nExample: An',
    groups: ['Personal'],
  },
  {
    value: 'lastName',
    displayName: 'Last Name',
    description: 'Person last name.\nExample: Nguyen',
    groups: ['Personal'],
  },
  {
    value: 'gender',
    displayName: 'Gender',
    description: 'Gender label.\nExample: male / female',
    groups: ['Personal'],
  },
  {
    value: 'email',
    displayName: 'Email',
    description: 'Email address.\nExample: user@example.com',
    groups: ['Personal', 'IT'],
  },
  {
    value: 'phoneNumber',
    displayName: 'Phone Number',
    description: 'Phone number.\nExample: 0901234567',
    groups: ['Personal'],
  },
  {
    value: 'address',
    displayName: 'Address',
    description: 'Street address.\nExample: 123 Nguyen Hue, District 1',
    groups: ['Personal'],
  },
  {
    value: 'city',
    displayName: 'City',
    description: 'City name.\nExample: Ho Chi Minh City',
    groups: ['Personal'],
  },
  {
    value: 'country',
    displayName: 'Country',
    description: 'Country name.\nExample: Vietnam',
    groups: ['Personal'],
  },
  {
    value: 'zipCode',
    displayName: 'Zip Code',
    description: 'Postal code.\nExample: 700000',
    groups: ['Personal'],
  },
  {
    value: 'companyName',
    displayName: 'Company Name',
    description: 'Company name.\nExample: Acme Corp',
    groups: ['Personal', 'Commerce'],
  },
  {
    value: 'jobTitle',
    displayName: 'Job Title',
    description: 'Job title.\nExample: Software Engineer',
    groups: ['Personal'],
  },
  {
    value: 'creditCardNumber',
    displayName: 'Credit Card #',
    description: 'Credit card number.\nExample: 4017959045824',
    groups: ['Commerce'],
  },
  {
    value: 'creditCardType',
    displayName: 'Credit Card Type',
    description: 'Card issuer name.\nExample: visa',
    groups: ['Commerce'],
  },
  {
    value: 'currency',
    displayName: 'Currency',
    description: 'Currency name.\nExample: Dollar',
    groups: ['Commerce'],
  },
  {
    value: 'currencyCode',
    displayName: 'Currency Code',
    description: 'Currency code.\nExample: USD',
    groups: ['Commerce'],
  },
  {
    value: 'departmentRetail',
    displayName: 'Department (Retail)',
    description: 'Retail department.\nExample: Grocery',
    groups: ['Commerce'],
  },
  {
    value: 'iban',
    displayName: 'IBAN',
    description: 'International bank number.\nExample: FR76 5960 2948 07N1 L9TC PVYX E17',
    groups: ['Commerce', 'IT'],
  },
  {
    value: 'productCategory',
    displayName: 'Product Category',
    description: 'Top-level product category.\nExample: Toys',
    groups: ['Commerce'],
  },
  {
    value: 'productDescription',
    displayName: 'Product Description',
    description: 'Product marketing text.\nExample: Savory lentil chips',
    groups: ['Commerce'],
  },
  {
    value: 'productName',
    displayName: 'Product Name',
    description: 'Product display name.\nExample: Classic Black Trousers',
    groups: ['Commerce'],
  },
  {
    value: 'productSubcategory',
    displayName: 'Product Subcategory',
    description: 'Detailed product category.\nExample: Gourmet Snacks',
    groups: ['Commerce'],
  },
  {
    value: 'stockIndustry',
    displayName: 'Stock Industry',
    description: 'Industry name.\nExample: Semiconductors',
    groups: ['Commerce'],
  },
  {
    value: 'stockMarket',
    displayName: 'Stock Market',
    description: 'Exchange name.\nExample: NASDAQ',
    groups: ['Commerce'],
  },
  {
    value: 'stockName',
    displayName: 'Stock Name',
    description: 'Listed company name.\nExample: Microsoft Corporation',
    groups: ['Commerce'],
  },
  {
    value: 'stockSector',
    displayName: 'Stock Sector',
    description: 'Sector name.\nExample: Technology',
    groups: ['Commerce'],
  },
  {
    value: 'stockSymbol',
    displayName: 'Stock Symbol',
    description: 'Ticker symbol.\nExample: MSFT',
    groups: ['Commerce', 'IT'],
  },
  {
    value: 'appBundleId',
    displayName: 'App Bundle ID',
    description: 'Three-part app id.\nExample: com.microsoft.prodder',
    groups: ['IT'],
  },
  {
    value: 'appName',
    displayName: 'App Name',
    description: 'Application name.\nExample: PowerFlex',
    groups: ['IT'],
  },
  {
    value: 'appVersion',
    displayName: 'App Version',
    description: 'Version number string.\nExample: 2.14.7',
    groups: ['IT'],
  },
  {
    value: 'base64ImageUrl',
    displayName: 'Base64 Image URL',
    description: 'Data URI image.\nExample: data:image/png;base64,...',
    groups: ['IT'],
  },
  {
    value: 'domainName',
    displayName: 'Domain Name',
    description: 'Internet domain name.\nExample: google.com',
    groups: ['IT'],
  },
  {
    value: 'dummyImageUrl',
    displayName: 'Dummy Image URL',
    description: 'Placeholder image URL.\nExample: https://dummyimage.com/250x100',
    groups: ['IT'],
  },
  {
    value: 'fileName',
    displayName: 'File Name',
    description: 'Generated file name.\nExample: report.csv',
    groups: ['IT'],
  },
  {
    value: 'ipAddressV4',
    displayName: 'IP Address v4',
    description: 'IPv4 address.\nExample: 121.150.202.132',
    groups: ['IT'],
  },
  {
    value: 'ipAddressV4Cidr',
    displayName: 'IP Address v4 CIDR',
    description: 'IPv4 CIDR block.\nExample: 188.245.97.43/27',
    groups: ['IT'],
  },
  {
    value: 'ipAddressV6',
    displayName: 'IP Address v6',
    description: 'IPv6 address.\nExample: 770:44c0:1c4:9996:2fd:6907:3045:9627',
    groups: ['IT'],
  },
  {
    value: 'ipAddressV6Cidr',
    displayName: 'IP Address v6 CIDR',
    description: 'IPv6 CIDR block.\nExample: 9ea4:.../115',
    groups: ['IT'],
  },
  {
    value: 'macAddress',
    displayName: 'MAC Address',
    description: 'MAC address.\nExample: 2C:D6:9B:77:E5:0B',
    groups: ['IT'],
  },
  {
    value: 'md5',
    displayName: 'MD5',
    description: 'Hex MD5 hash.\nExample: 5d41402abc4b2a76b9719d911017c592',
    groups: ['IT'],
  },
  {
    value: 'mimeType',
    displayName: 'MIME Type',
    description: 'File MIME type.\nExample: application/pdf',
    groups: ['IT'],
  },
  {
    value: 'sha1',
    displayName: 'SHA1',
    description: 'Hex SHA1 hash.\nExample: 2fd4e1c67a2d28fced849ee1bb76e7391b93eb12',
    groups: ['IT'],
  },
  {
    value: 'sha256',
    displayName: 'SHA256',
    description: 'Hex SHA256 hash.\nExample: 9f86d081884c7d659a2feaa0c55ad015...',
    groups: ['IT'],
  },
  {
    value: 'topLevelDomain',
    displayName: 'Top Level Domain',
    description: 'Top-level domain.\nExample: com',
    groups: ['IT'],
  },
  {
    value: 'userAgent',
    displayName: 'User Agent',
    description: 'Browser or bot user agent.\nExample: Mozilla/5.0 ...',
    groups: ['IT'],
  },
  {
    value: 'username',
    displayName: 'Username',
    description: 'Login username.\nExample: twilliams',
    groups: ['IT', 'Personal'],
  },
];

export const SQL_TYPE_DEFAULT_CLASSIFICATION: Record<string, SemanticDataType> = {
  int: 'number',
  integer: 'number',
  bigint: 'number',
  smallint: 'number',
  tinyint: 'number',
  decimal: 'number',
  numeric: 'number',
  float: 'number',
  real: 'number',
  double: 'number',
  uniqueidentifier: 'guid',
  uuid: 'guid',
  bit: 'boolean',
  boolean: 'boolean',
  bool: 'boolean',
  date: 'dateTime',
  datetime: 'dateTime',
  timestamp: 'dateTime',
  char: 'text',
  varchar: 'text',
  text: 'text',
  nchar: 'text',
  nvarchar: 'text',
};

export function normalizeSqlType(dbType: string): string {
  return dbType
    .toLowerCase()
    .replace(/\(.+\)/g, '')
    .trim();
}
