import fs from 'fs';
import path from 'path';
import { GeneratedTableRows, SqlProvider } from '../core/types';
import dayjs from 'dayjs';

const MAX_ROWS_PER_INSERT = 1000;
const TOOL_VERSION =
  (
    JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../package.json'), 'utf-8')) as {
      version?: string;
    }
  ).version ?? 'unknown';

function sqlValue(value: string | number | boolean | null): string {
  if (value === null) {
    return 'NULL';
  }
  if (typeof value === 'number') {
    return String(value);
  }
  if (typeof value === 'boolean') {
    return value ? '1' : '0';
  }
  return `'${value.replace(/'/g, "''")}'`;
}

function chunkRows<T>(items: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size));
  }
  return chunks;
}

function buildInsertSql(tableData: GeneratedTableRows): string {
  if (tableData.rows.length === 0) {
    return '';
  }

  const columns = Object.keys(tableData.rows[0]);
  const rowChunks = chunkRows(tableData.rows, MAX_ROWS_PER_INSERT);
  const insertStatements = rowChunks.map((rowChunk) => {
    const valueLines = rowChunk.map((row) => {
      const values = columns.map((column) => sqlValue(row[column] ?? null)).join(', ');
      return `(${values})`;
    });

    return [
      `INSERT INTO ${tableData.tableName} (${columns.join(', ')}) VALUES`,
      `${valueLines.join(',\n')};`,
    ].join('\n');
  });

  return [...insertStatements, ''].join('');
}

function buildTransactionWrapper(sqlProvider?: SqlProvider | ''): {
  prefix: string[];
  suffix: string[];
} {
  switch (sqlProvider) {
    case 'sqlserver':
      return {
        prefix: ['BEGIN TRANSACTION;', ''],
        suffix: ['', 'COMMIT TRANSACTION;'],
      };
    case 'postgres':
      return {
        prefix: ['BEGIN;', ''],
        suffix: ['', 'COMMIT;'],
      };
    case 'mysql':
      return {
        prefix: ['START TRANSACTION;', ''],
        suffix: ['', 'COMMIT;'],
      };
    default:
      return {
        prefix: [],
        suffix: [],
      };
  }
}

function buildFileHeader(
  createdAt: string,
  totalRecords: number,
  sqlProvider?: SqlProvider | '',
): string {
  const providerLabel =
    sqlProvider === 'sqlserver'
      ? 'SQL Server'
      : sqlProvider === 'postgres'
        ? 'Postgres'
        : sqlProvider === 'mysql'
          ? 'MySQL'
          : null;

  return [
    `/**********************************************************************`,
    `- Generated by SQL Data Generator Tool v${TOOL_VERSION}`,
    `- Creation time: ${dayjs(createdAt).format('YYYY-MM-DD HH:mm:ss Z')}`,
    `- SQL Provider: ${providerLabel || '[WARNING] SQL Provider is not selected. Transaction wrapper was not added.'.toUpperCase()}`,
    `- Affected rows: ${totalRecords}`,
    `**********************************************************************/`,
  ]
    .filter((x) => x)
    .join('\n');
}

export interface SqlFileArtifact {
  fileName: string;
  content: string;
}

export function buildGeneratedSqlHeader(
  createdAt: string,
  totalRecords: number,
  sqlProvider?: SqlProvider | '',
): string {
  return buildFileHeader(createdAt, totalRecords, sqlProvider);
}

export function buildInsertFileArtifacts(
  tableRows: GeneratedTableRows[],
  sqlProvider?: SqlProvider | '',
  options?: { includeHeader?: boolean; includeTransaction?: boolean },
): SqlFileArtifact[] {
  const createdAt = new Date().toISOString();
  const includeHeader = options?.includeHeader ?? true;
  const includeTransaction = options?.includeTransaction ?? true;
  const totalRecords = tableRows.reduce((sum, tableData) => sum + tableData.rows.length, 0);
  return tableRows.map((tableData, index) => {
    const order = String(index + 1).padStart(3, '0');
    const insertSql = buildInsertSql(tableData);
    const transactionWrapper = includeTransaction
      ? buildTransactionWrapper(sqlProvider)
      : { prefix: [], suffix: [] };
    return {
      fileName: `${order}_${tableData.tableName}.sql`,
      content: [
        includeHeader ? buildFileHeader(createdAt, totalRecords, sqlProvider) : '',
        ...transactionWrapper.prefix,
        insertSql,
        ...transactionWrapper.suffix,
      ]
        .filter((part) => part.length > 0)
        .join('\n'),
    };
  });
}

export function writeInsertFiles(tableRows: GeneratedTableRows[], outputDir: string): string[] {
  fs.mkdirSync(outputDir, { recursive: true });
  const files: string[] = [];

  const artifacts = buildInsertFileArtifacts(tableRows);
  artifacts.forEach((artifact) => {
    const fullPath = path.join(outputDir, artifact.fileName);
    fs.writeFileSync(fullPath, artifact.content, 'utf-8');
    files.push(fullPath);
  });

  return files;
}
