export const SEMANTIC_DATA_TYPES = [
  'unknown',
  'guid',
  'digitSequence',
  'formula',
  'regularExpression',
  'sequence',
  'appBundleId',
  'appName',
  'appVersion',
  'base64ImageUrl',
  'creditCardNumber',
  'creditCardType',
  'currency',
  'currencyCode',
  'departmentRetail',
  'domainName',
  'dummyImageUrl',
  'fileName',
  'iban',
  'ipAddressV4',
  'ipAddressV4Cidr',
  'ipAddressV6',
  'ipAddressV6Cidr',
  'macAddress',
  'md5',
  'mimeType',
  'productCategory',
  'productDescription',
  'productGrocery',
  'productName',
  'productSubcategory',
  'mobileDeviceBrand',
  'mobileDeviceModel',
  'mobileDeviceOs',
  'mobileDeviceReleaseDate',
  'movieGenres',
  'movieTitle',
  'sha1',
  'sha256',
  'stockIndustry',
  'stockMarket',
  'stockName',
  'stockSector',
  'stockSymbol',
  'topLevelDomain',
  'userAgent',
  'username',
  'fullName',
  'firstName',
  'lastName',
  'gender',
  'email',
  'phoneNumber',
  'address',
  'streetAddress',
  'streetName',
  'streetNumber',
  'streetSuffix',
  'city',
  'country',
  'countryCode',
  'latitude',
  'longitude',
  'state',
  'stateAbbrev',
  'zipCode',
  'companyName',
  'jobTitle',
  'url',
  'dateTime',
  'time',
  'color',
  'hexColor',
  'password',
  'passwordHash',
  'timeZone',
  'boolean',
  'number',
  'text',
] as const;

export type SemanticDataType = (typeof SEMANTIC_DATA_TYPES)[number];

export const DATA_TYPE_GROUPS = [
  'Basic',
  'Advanced',
  'Personal',
  'Commerce',
  'IT',
  'Location',
  'Products',
  'Table Primary Key',
] as const;

export type DataTypeGroup = (typeof DATA_TYPE_GROUPS)[number];
