import fs from 'fs';
import path from 'path';
import { AppStorageState } from './models';

const DEFAULT_PROJECT = {
  id: 'local',
  name: 'local',
  description: 'Initial project, auto generated by app.',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
};

const defaultState: AppStorageState = {
  projects: [DEFAULT_PROJECT],
  generationRequests: [],
  customListTypes: [],
};

function ensureDefaultProject(state: AppStorageState): AppStorageState {
  if (state.projects.length > 0) {
    return state;
  }

  return {
    ...state,
    projects: [DEFAULT_PROJECT],
  };
}

export class JsonFileStorage {
  private readonly filePath: string;

  constructor(filePath: string) {
    this.filePath = filePath;
  }

  read(): AppStorageState {
    if (!fs.existsSync(this.filePath)) {
      return defaultState;
    }

    const raw = fs.readFileSync(this.filePath, 'utf-8').trim();
    if (!raw) {
      return defaultState;
    }

    const parsed = JSON.parse(raw) as AppStorageState;
    return ensureDefaultProject({
      projects: parsed.projects ?? [],
      generationRequests: parsed.generationRequests ?? [],
      customListTypes: parsed.customListTypes ?? [],
    });
  }

  write(state: AppStorageState): void {
    const folder = path.dirname(this.filePath);
    fs.mkdirSync(folder, { recursive: true });
    fs.writeFileSync(this.filePath, JSON.stringify(state, null, 2), 'utf-8');
  }
}
